import { jsPDF } from "jspdf";

export function downloadReport(text) {
  const doc = new jsPDF();

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("MIS Analytics Copilot", 20, 20);

  // Subtitle
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Executive Business Report", 20, 30);

  // Date
  doc.setFontSize(11);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    40
  );

  // Divider
  doc.line(20, 45, 190, 45);

  // Report Content
  doc.setFontSize(12);

  const lines = doc.splitTextToSize(text, 170);

  doc.text(lines, 20, 55);

  // Footer
  doc.setFontSize(10);

  doc.text(
    "Generated by MIS Analytics Copilot AI",
    20,
    285
  );

  doc.save("Executive_Report.pdf");
}